const L10N = {
    it:{
      sub:'Segui i passi a sinistra: prima i dati, poi lo scenario, poi le quattro tavole. Doppio clic o Invio per chiudere una linea.',
      gStato:'Stato', statoPrevisto:'Previsto', statoAttivo:'In atto',
      nIntervento:'N. intervento', nDos:'DOS', dosAiuto:'Cifre o lettere, fino a sei. Es. VF 12A4',
      ventoLeggo:'Lettura del vento in corso…',
      ventoErrore:'Vento non disponibile: {e}',
      gPunti:'Punti', gLinee:'Linee', gAree:'Aree',
      areeFuori:'Perimetri fuori tavola SITAC: servono al calcolo di superficie e perimetro.',
      gModifica:'Modifica', gMappa:'Mappa e dati', gEsporta:'Esportazione',
      legenda:'Legenda', legVuota:'Nessun elemento sulla mappa.',
      bSposta:'Sposta', bElimina:'Elimina', bAnnulla:'Annulla ultimo', bPulisci:'Cancella tutto',
      bSfondo:'Sfondo', bImporta:'Importa GeoJSON', bStampa:'Esporta/Stampa PDF', bExpGeoJSON:'Esporta GeoJSON', bExpKML:'Esporta KML', bCentra:'Centra sulla mia posizione',
      pronto:'Pronto.\nApri un passo a sinistra e scegli uno strumento.',
      spento:'Strumento disattivato.',
      suggLinea:'Clic per i vertici, doppio clic per chiudere.',
      suggArea:'Clic per i vertici, clic sul primo per chiudere.',
      suggSimbolo:'Clic sulla mappa per posizionare.',
      chiediSigla:'Sigla o testo da scrivere nel simbolo',
      chiediNota:'Testo dell\u2019annotazione',
      chiediDirezione:'Clicca sulla mappa dove punta il simbolo.\nPoi puoi trascinare la maniglia.',
      confPulisci:'Cancellare tutti gli elementi disegnati?',
      ok:'Conferma', annulla:'Annulla', titoloModale:'FireOps VVF — SITAC',
      modOn:'Modifica attiva.\nTrascina i vertici o i simboli.', modOff:'Modifica disattivata.',
      elimOn:'Eliminazione attiva.\nClic su un elemento per rimuoverlo.', elimOff:'Eliminazione disattivata.',
      nienteAnnulla:'Niente da annullare.', giaVuota:'La mappa è già vuota.',
      sfondo:'Sfondo: {n}', localizzo:'Localizzazione in corso…',
      posizione:'Posizione: {lat}, {lon}\n±{m} m',
      posErrore:'Posizione non disponibile.\nSu http non locale il GPS è bloccato.',
      nienteExport:'Niente da esportare.',
      geojsonFatto:'GeoJSON: {n} elementi.\nÈ l\'unico formato che rientra qui identico.',
      kmlFatto:'KML: {n} elementi ({a} poligoni).\nApribile in QGIS e Google Earth.',
      fileErrato:'File non valido: {e}', importati:'Importati {n} elementi.',
      conteggio:'{p} punti · {l} linee · {a} aree',
      superficie:'\nSuperficie totale: {v} ha', perimetro:'\nPerimetro totale: {v} km',
      areaDi:'Superficie {a} ha · perimetro {p} km', lunghezzaDi:'Lunghezza {v} km',
      kmlDoc:'SITAC incendio boschivo', kmlAree:'Aree', kmlLinee:'Linee', kmlSimboli:'Simboli',
      sfSat:'Satellite', sfTopo:'Topografico', sfStrada:'Stradale',
      stTitolo:'SITAC — Incendio boschivo', stData:'Redatta il {d}',
      importAree:'Importati {n} perimetri.', importScarti:'\n{n} elementi non poligonali ignorati.',
      importNiente:'Nessun poligono nel file: si importano solo aree.',
      conoPendenza:'Dalla linea di massima pendenza',
      conoPendenzaNota:'Fig. 4: senza vento la bisettrice \u00e8 la massima salita, letta dal rilievo.',
      pendLeggo:'Lettura del rilievo attorno al fronte\u2026',
      pendPiatto:'Terreno quasi piano attorno al fronte: qui la pendenza non guida la propagazione.',
      pendTrovata:'Massima salita verso {a}\u00b0 · pendenza {p}%',
      pendFonte:'massima pendenza',
      pendVelQuale:'Da dove viene la velocit\u00e0 di avanzamento?',
      pendVelPercorso:'Dal terreno gi\u00e0 percorso',
      pendVelPercorsoNota:'{d} m dall\u2019innesco al fronte, divisi per le ore trascorse.',
      pendVelVista:'Stimata a vista', pendVelVistaNota:'In metri all\u2019ora, guardando il fronte.',
      chiediOraInnesco:'Ora d\u2019innesco (hh:mm)', oraErrata:'Ora non valida.',
      chiediMetriOra:'Avanzamento del fronte in metri all\u2019ora\n300 = come vento 10 km/h · 900 = come 30 km/h · 1800 = come 60 km/h',
      conoPendFatto:'Cono {a}\u00b0 su massima salita {d}\u00b0 (pendenza {p}%)\nFronte a {m} m in un\u2019ora — velocit\u00e0 stimata, non SI.TA.C.',
    },
    en:{
      sub:'Follow the steps on the left: data first, then the scenario, then the four tables. Double-click or Enter closes a line.',
      gStato:'State', statoPrevisto:'Planned', statoAttivo:'Active',
      nIntervento:'Incident no.', nDos:'WIC', dosAiuto:'Digits or letters, up to six. E.g. VF 12A4',
      ventoLeggo:'Reading wind data…',
      ventoErrore:'Wind unavailable: {e}',
      gPunti:'Points', gLinee:'Lines', gAree:'Areas',
      areeFuori:'Polygons outside the SITAC table: used to compute area and perimeter.',
      gModifica:'Edit', gMappa:'Map and data', gEsporta:'Export',
      legenda:'Legend', legVuota:'Nothing on the map yet.',
      bSposta:'Move', bElimina:'Delete', bAnnulla:'Undo last', bPulisci:'Clear all',
      bSfondo:'Basemap', bImporta:'Import GeoJSON', bStampa:'Export/Print PDF',
      bExpGeoJSON:'Export GeoJSON', bExpKML:'Export KML', bCentra:'Centre on my position',
      pronto:'Ready.\nOpen a step on the left and pick a tool.',
      spento:'Tool switched off.',
      suggLinea:'Click each vertex, double-click to close.',
      suggArea:'Click each vertex, click the first one to close.',
      suggSimbolo:'Click the map to place it.',
      chiediSigla:'Label to write inside the symbol',
      chiediNota:'Note text',
      chiediDirezione:'Click on the map where the symbol points.\nThen you can drag the handle.',
      confPulisci:'Delete every drawn element?',
      ok:'Confirm', annulla:'Cancel', titoloModale:'FireOps VVF — SITAC',
      modOn:'Edit mode on.\nDrag vertices or symbols.', modOff:'Edit mode off.',
      elimOn:'Delete mode on.\nClick an element to remove it.', elimOff:'Delete mode off.',
      nienteAnnulla:'Nothing to undo.', giaVuota:'The map is already empty.',
      sfondo:'Basemap: {n}', localizzo:'Locating…',
      posizione:'Position: {lat}, {lon}\n±{m} m',
      posErrore:'Position unavailable.\nGPS is blocked on non-local http.',
      nienteExport:'Nothing to export.',
      geojsonFatto:'GeoJSON: {n} elements.\nThe only format that comes back in unchanged.',
      kmlFatto:'KML: {n} elements ({a} polygons).\nOpens in QGIS and Google Earth.',
      fileErrato:'Invalid file: {e}', importati:'{n} elements imported.',
      conteggio:'{p} points · {l} lines · {a} areas',
      superficie:'\nTotal area: {v} ha', perimetro:'\nTotal perimeter: {v} km',
      areaDi:'Area {a} ha · perimeter {p} km', lunghezzaDi:'Length {v} km',
      kmlDoc:'Wildfire SITAC', kmlAree:'Areas', kmlLinee:'Lines', kmlSimboli:'Symbols',
      sfSat:'Satellite', sfTopo:'Topographic', sfStrada:'Street',
      stTitolo:'SITAC — Wildfire', stData:'Drawn on {d}',
      importAree:'{n} perimeters imported.', importScarti:'\n{n} non-polygon elements ignored.',
      importNiente:'No polygons in the file: only areas are imported.',
      conoPendenza:'From the line of steepest slope',
      conoPendenzaNota:'Fig. 4: with no wind the bisector is the steepest ascent, read from the terrain.',
      pendLeggo:'Reading the terrain around the front…',
      pendPiatto:'Nearly flat ground around the front: slope does not drive propagation here.',
      pendTrovata:'Steepest ascent towards {a}° · slope {p}%',
      pendFonte:'steepest slope',
      pendVelQuale:'Where does the rate of spread come from?',
      pendVelPercorso:'From the ground already burned',
      pendVelPercorsoNota:'{d} m from the origin to the front, divided by the hours elapsed.',
      pendVelVista:'Estimated by eye', pendVelVistaNota:'In metres per hour, looking at the front.',
      chiediOraInnesco:'Time of ignition (hh:mm)', oraErrata:'Invalid time.',
      chiediMetriOra:'Rate of spread in metres per hour\n300 = same as 10 km/h wind · 900 = as 30 km/h · 1800 = as 60 km/h',
      conoPendFatto:'Cone {a}° on steepest ascent {d}° (slope {p}%)\nFront at {m} m in one hour — estimated rate, not SI.TA.C.'
    },
    fr:{
      sub:'Suivez les étapes à gauche : les données, puis la situation, puis les quatre tableaux. Double-clic ou Entrée pour fermer une ligne.',
      gStato:'État', statoPrevisto:'Prévu', statoAttivo:'En cours',
      nIntervento:'N° d\'intervention', nDos:'COS', dosAiuto:'Chiffres ou lettres, jusqu\u2019à six. Ex. VF 12A4',
      ventoLeggo:'Lecture du vent en cours…',
      ventoErrore:'Vent indisponible : {e}',
      gPunti:'Points', gLinee:'Lignes', gAree:'Zones',
      areeFuori:'Polygones hors tableau SITAC : ils servent au calcul de la surface et du périmètre.',
      gModifica:'Modifier', gMappa:'Carte et données', gEsporta:'Exportation',
      legenda:'Légende', legVuota:'Rien sur la carte pour le moment.',
      bSposta:'Déplacer', bElimina:'Supprimer', bAnnulla:'Annuler le dernier', bPulisci:'Tout effacer',
      bSfondo:'Fond de carte', bImporta:'Importer GeoJSON', bStampa:'Exporter/Imprimer PDF',
      bExpGeoJSON:'Exporter GeoJSON', bExpKML:'Exporter KML', bCentra:'Centrer sur ma position',
      pronto:'Prêt.\nOuvrez une étape à gauche et choisissez un outil.',
      spento:'Outil désactivé.',
      suggLinea:'Cliquez chaque sommet, double-clic pour fermer.',
      suggArea:'Cliquez chaque sommet, cliquez le premier pour fermer.',
      suggSimbolo:'Cliquez sur la carte pour le poser.',
      chiediSigla:'Texte à inscrire dans le symbole',
      chiediNota:'Texte de l\u2019annotation',
      chiediDirezione:'Cliquez sur la carte dans la direction du symbole.\nVous pourrez ensuite déplacer la poignée.',
      confPulisci:'Supprimer tous les éléments dessinés ?',
      ok:'Confirmer', annulla:'Annuler', titoloModale:'FireOps VVF — SITAC',
      modOn:'Modification active.\nDéplacez les sommets ou les symboles.', modOff:'Modification désactivée.',
      elimOn:'Suppression active.\nCliquez un élément pour le retirer.', elimOff:'Suppression désactivée.',
      nienteAnnulla:'Rien à annuler.', giaVuota:'La carte est déjà vide.',
      sfondo:'Fond : {n}', localizzo:'Localisation en cours…',
      posizione:'Position : {lat}, {lon}\n±{m} m',
      posErrore:'Position indisponible.\nLe GPS est bloqué en http non local.',
      nienteExport:'Rien à exporter.',
      geojsonFatto:'GeoJSON : {n} éléments.\nSeul format qui revient ici à l\'identique.',
      kmlFatto:'KML : {n} éléments ({a} polygones).\nS\'ouvre dans QGIS et Google Earth.',
      fileErrato:'Fichier invalide : {e}', importati:'{n} éléments importés.',
      conteggio:'{p} points · {l} lignes · {a} zones',
      superficie:'\nSurface totale : {v} ha', perimetro:'\nPérimètre total : {v} km',
      areaDi:'Surface {a} ha · périmètre {p} km', lunghezzaDi:'Longueur {v} km',
      kmlDoc:'SITAC feu de forêt', kmlAree:'Zones', kmlLinee:'Lignes', kmlSimboli:'Symboles',
      sfSat:'Satellite', sfTopo:'Topographique', sfStrada:'Routier',
      stTitolo:'SITAC — Feu de forêt', stData:'Établie le {d}',
      importAree:'{n} périmètres importés.', importScarti:'\n{n} éléments non polygonaux ignorés.',
      importNiente:'Aucun polygone dans le fichier : seules les zones sont importées.',
      conoPendenza:'Depuis la ligne de plus grande pente',
      conoPendenzaNota:'Fig. 4 : sans vent, la bissectrice est la ligne de plus grande montée, lue sur le relief.',
      pendLeggo:'Lecture du relief autour du front\u2026',
      pendPiatto:'Terrain presque plat autour du front : ici la pente ne guide pas la propagation.',
      pendTrovata:'Plus grande montée vers {a}\u00b0 · pente {p}%',
      pendFonte:'plus grande pente',
      pendVelQuale:'D\u2019où vient la vitesse de propagation ?',
      pendVelPercorso:'Du terrain déjà parcouru',
      pendVelPercorsoNota:'{d} m de l\u2019origine au front, divisés par les heures écoulées.',
      pendVelVista:'Estimée à vue', pendVelVistaNota:'En mètres par heure, en regardant le front.',
      chiediOraInnesco:'Heure de départ de feu (hh:mm)', oraErrata:'Heure invalide.',
      chiediMetriOra:'Vitesse du front en mètres par heure\n300 = comme un vent de 10 km/h · 900 = comme 30 km/h · 1800 = comme 60 km/h',
      conoPendFatto:'C\u00f4ne {a}\u00b0 sur la plus grande montée {d}\u00b0 (pente {p}%)\nFront à {m} m en une heure — vitesse estimée, non SI.TA.C.'
    },
    es:{
      sub:'Sigue los pasos de la izquierda: primero los datos, luego la situación, luego las cuatro tablas. Doble clic o Intro para cerrar una línea.',
      gStato:'Estado', statoPrevisto:'Previsto', statoAttivo:'En curso',
      nIntervento:'N.º de intervención', nDos:'DOE', dosAiuto:'Cifras o letras, hasta seis. P. ej. VF 12A4',
      ventoLeggo:'Leyendo el viento…',
      ventoErrore:'Viento no disponible: {e}',
      gPunti:'Puntos', gLinee:'Líneas', gAree:'Áreas',
      areeFuori:'Polígonos fuera de la tabla SITAC: sirven para calcular superficie y perímetro.',
      gModifica:'Editar', gMappa:'Mapa y datos', gEsporta:'Exportación',
      legenda:'Leyenda', legVuota:'Todavía no hay nada en el mapa.',
      bSposta:'Mover', bElimina:'Eliminar', bAnnulla:'Deshacer último', bPulisci:'Borrar todo',
      bSfondo:'Fondo', bImporta:'Importar GeoJSON', bStampa:'Exportar/Imprimir PDF',
      bExpGeoJSON:'Exportar GeoJSON', bExpKML:'Exportar KML', bCentra:'Centrar en mi posición',
      pronto:'Listo.\nAbre un paso a la izquierda y elige una herramienta.',
      spento:'Herramienta desactivada.',
      suggLinea:'Haz clic en cada vértice, doble clic para cerrar.',
      suggArea:'Haz clic en cada vértice, clic en el primero para cerrar.',
      suggSimbolo:'Haz clic en el mapa para colocarlo.',
      chiediSigla:'Texto que va dentro del símbolo',
      chiediNota:'Texto de la anotación',
      chiediDirezione:'Haz clic en el mapa hacia donde apunta el símbolo.\nLuego puedes arrastrar el tirador.',
      confPulisci:'¿Borrar todos los elementos dibujados?',
      ok:'Confirmar', annulla:'Cancelar', titoloModale:'FireOps VVF — SITAC',
      modOn:'Edición activa.\nArrastra los vértices o los símbolos.', modOff:'Edición desactivada.',
      elimOn:'Eliminación activa.\nHaz clic en un elemento para quitarlo.', elimOff:'Eliminación desactivada.',
      nienteAnnulla:'Nada que deshacer.', giaVuota:'El mapa ya está vacío.',
      sfondo:'Fondo: {n}', localizzo:'Localizando…',
      posizione:'Posición: {lat}, {lon}\n±{m} m',
      posErrore:'Posición no disponible.\nEn http no local el GPS está bloqueado.',
      nienteExport:'Nada que exportar.',
      geojsonFatto:'GeoJSON: {n} elementos.\nEl único formato que vuelve aquí idéntico.',
      kmlFatto:'KML: {n} elementos ({a} polígonos).\nSe abre en QGIS y Google Earth.',
      fileErrato:'Archivo no válido: {e}', importati:'{n} elementos importados.',
      conteggio:'{p} puntos · {l} líneas · {a} áreas',
      superficie:'\nSuperficie total: {v} ha', perimetro:'\nPerímetro total: {v} km',
      areaDi:'Superficie {a} ha · perímetro {p} km', lunghezzaDi:'Longitud {v} km',
      kmlDoc:'SITAC incendio forestal', kmlAree:'Áreas', kmlLinee:'Líneas', kmlSimboli:'Símbolos',
      sfSat:'Satélite', sfTopo:'Topográfico', sfStrada:'Callejero',
      stTitolo:'SITAC — Incendio forestal', stData:'Redactada el {d}',
      importAree:'{n} perímetros importados.', importScarti:'\n{n} elementos no poligonales ignorados.',
      importNiente:'Ningún polígono en el archivo: solo se importan áreas.',
      conoPendenza:'Desde la línea de máxima pendiente',
      conoPendenzaNota:'Fig. 4: sin viento la bisectriz es la máxima subida, leída del relieve.',
      pendLeggo:'Leyendo el relieve alrededor del frente\u2026',
      pendPiatto:'Terreno casi llano alrededor del frente: aquí la pendiente no guía la propagación.',
      pendTrovata:'Máxima subida hacia {a}\u00b0 · pendiente {p}%',
      pendFonte:'máxima pendiente',
      pendVelQuale:'¿De dónde viene la velocidad de avance?',
      pendVelPercorso:'Del terreno ya recorrido',
      pendVelPercorsoNota:'{d} m desde el origen al frente, divididos por las horas transcurridas.',
      pendVelVista:'Estimada a ojo', pendVelVistaNota:'En metros por hora, mirando el frente.',
      chiediOraInnesco:'Hora de inicio (hh:mm)', oraErrata:'Hora no válida.',
      chiediMetriOra:'Avance del frente en metros por hora\n300 = como viento de 10 km/h · 900 = como 30 km/h · 1800 = como 60 km/h',
      conoPendFatto:'Cono {a}\u00b0 sobre máxima subida {d}\u00b0 (pendiente {p}%)\nFrente a {m} m en una hora — velocidad estimada, no SI.TA.C.'
    }
  };